// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DiscordTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver(@"C:/");
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void discord() {
    driver.Navigate().GoToUrl("https://discord.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    driver.FindElement(By.CssSelector(".wrapperMobile-3gWL2X .logo-3LF899")).Click();
    driver.FindElement(By.CssSelector(".menuIcon-3UgAfy path")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".menuIcon-3UgAfy path"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".link-3XMvoR:nth-child(2) > .text-3U-SDd")).Click();
    driver.FindElement(By.CssSelector(".wrapperMobile-3gWL2X path:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".wrapperMobile-3gWL2X path:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".menuIcon-3UgAfy path")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".menuIcon-3UgAfy path"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.LinkText("Загрузить")).Click();
  }
}
