// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RedditTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver(@"C:/");
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void reddit() {
    driver.Navigate().GoToUrl("https://www.reddit.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    {
      var element = driver.FindElement(By.CssSelector(".\\_3i8KqqBirs9EBhAQeUrIDl .\\_2kQHCzdwbwXs8DKZ0KmhwB"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".M2Hk_S2yvXpsNPfZMBMur:nth-child(2) > .\\_1lwNBHmCQJObvqs1fXKSYR")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".\\_1s79QnBguPbckxiiPvFXGP > .\\_1lwNBHmCQJObvqs1fXKSYR"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".M2Hk_S2yvXpsNPfZMBMur:nth-child(1) > .\\_1lwNBHmCQJObvqs1fXKSYR")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".M2Hk_S2yvXpsNPfZMBMur:nth-child(1) > .\\_1lwNBHmCQJObvqs1fXKSYR"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".\\_1s79QnBguPbckxiiPvFXGP > .\\_1lwNBHmCQJObvqs1fXKSYR")).Click();
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
  }
}
