// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SteambuyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver(@"C:/");
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void steambuy() {
    driver.Navigate().GoToUrl("https://steambuy.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    {
      var element = driver.FindElement(By.CssSelector(".banner-img"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".logo__link > img"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
    driver.FindElement(By.Id("top_nav")).Click();
    driver.FindElement(By.LinkText("НАКОПИТЕЛЬНАЯ")).Click();
    driver.FindElement(By.CssSelector(".logo__link > img")).Click();
    driver.FindElement(By.Id("main_nav")).Click();
    {
      var element = driver.FindElement(By.CssSelector("#main_nav > .nav-toggle__bar:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector("#main_nav > .nav-toggle__bar:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".main-slider__item:nth-child(3) .main-slider__lg-png img")).Click();
    driver.FindElement(By.CssSelector(".logo__link > img")).Click();
  }
}
