// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TetssmtTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver(@"C:/");
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tetssmt() {
    driver.Navigate().GoToUrl("https://auto.ru/");
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    driver.FindElement(By.CssSelector(".Link_hovered > .IndexSuperMark__image")).Click();
    driver.FindElement(By.LinkText("Авто.ру")).Click();
    js.ExecuteScript("window.scrollTo(0,1600)");
    driver.FindElement(By.CssSelector(".Link_hovered > .IndexSuperMark__image")).Click();
    driver.FindElement(By.CssSelector(".Button_hovered > .Button__content")).Click();
    driver.FindElement(By.CssSelector(".MenuItem_hovered")).Click();
    driver.FindElement(By.CssSelector(".ListingCarsFilters-module__container")).Click();
    driver.FindElement(By.CssSelector(".Button_hovered > .Button__content")).Click();
    js.ExecuteScript("window.scrollTo(0,95)");
    {
      var element = driver.FindElement(By.CssSelector(".Link_hovered .ListingItemTitle-module__clicker"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.LinkText("Авто.ру")).Click();
  }
}
