// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VkTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver(@"C:/");
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void vk() {
    driver.Navigate().GoToUrl("https://vk.com/feed");
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    driver.FindElement(By.CssSelector("#l_msg .left_label")).Click();
    driver.FindElement(By.CssSelector(".\\_im_dialog_76984016 .nim-dialog--text-preview")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".\\_im_dialog_50173071 .nim-dialog--close"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".\\_im_dialog_50173071 .nim-dialog--cw")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    {
      var element = driver.FindElement(By.CssSelector(".im-page--header-icon_search"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector("svg:nth-child(2)")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
  }
}
