// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Vk
{
    [TestFixture]
    public class SteambuyTest : TestBase
    {
        [Test]
        public void steambuy()
        {
            app.Navigation.OpenHomePage();
            app.Navigation.CrossingTheBanner();
            app.driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
            app.Navigation.GoToBonusSystem();
            app.Navigation.GoHome();
            app.Navigation.NavToggle();
            app.Navigation.GoToCyberpunk();
            app.Navigation.GoHome();
        }
    }
}