// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SpotifyTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void spotify() {
    driver.Navigate().GoToUrl("https://www.spotify.com/ru-ru/");
    driver.Manage().Window.Size = new System.Drawing.Size(945, 1020);
    driver.FindElement(By.CssSelector(".mh-menu-closed")).Click();
    driver.FindElement(By.LinkText("Вход в аккаунт")).Click();
    driver.FindElement(By.Id("login-password")).SendKeys("McSpotface");
    driver.FindElement(By.Id("login-button")).Click();
    js.ExecuteScript("window.scrollTo(0,6)");
  }
}
