// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Vk
{
    [TestFixture]
    public class SteamSearchTest : TestBase
    {
        [Test]
        public void steamSearch()
        {
            OpenHomePage();
            driver.Manage().Window.Size = new System.Drawing.Size(945, 1020);
            SearchData search = new SearchData("Need for speed");
            SearchOfGame(search);
        }
    }
}