// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Vk
{
    [TestFixture]
    public class SteambuyTest : TestBase
    {
        [Test]
        public void steambuy()
        {
            OpenHomePage();
            CrossingTheBanner();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
            GoToBonusSystem();
            GoHome();
            NavToggle();
            GoToCyberpunk();
            GoHome();
        }
    }
}